app:
    resource: '@AppBundle/Controller/'
    type: annotation
changeCalculator:
    path:       /automaton/{model}/{method}/{amount}
    defaults:   { _controller: AppBundle:Default:changeCalculator }
    requirements:
        amount: '\d+'